name: Build and publish LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Compile a LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: report.tex
          compiler: pdflatex

      - name: Prepare a tag info for upcoming release
        id: info
        run: |
          echo "name=$(TZ=Asia/Yakutsk date +'%Y.%m.%d %H:%M')" >> $GITHUB_OUTPUT
          echo "tag=$(TZ=Asia/Yakutsk date +'%Y%.m.%d-%H.%M')" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.info.outputs.name }}
          tag_name: ${{ steps.info.outputs.tag }}
          files: report.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
