name: Build LaTeX document
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: report.tex
          compiler: pdflatex
      - name: Publish PDF
        uses: actions/upload-artifact@v4
        with:
          path: report.pdf
