name: Build and publish LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Compile a LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: report.tex
          compiler: pdflatex

      - name: Read current date and time
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: report.pdf
