name: Build and publish LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Compile a LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: report.tex
          compiler: pdflatex

      - name: Read current date and time
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ steps.datetime.outputs.datetime }}
          tag_name: ${{ github.ref }}
          body_path: report.pdf
